// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DairyControl.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928133820_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DairyControl.Domain.Entities.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("DairyControl.Domain.Entities.Proveedor", b =>
                {
                    b.OwnsMany("DairyControl.Domain.Entities.RecepcionLeche", "Recepciones", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProveedorId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("ProveedorId");

                            b1.ToTable("Recepciones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProveedorId");

                            b1.OwnsOne("DairyControl.Domain.ValueObjects.ParametrosCalidad", "Parametros", b2 =>
                                {
                                    b2.Property<Guid>("RecepcionLecheId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Acidez")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("decimal(5,2)");

                                    b2.Property<decimal>("Grasa")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("decimal(5,2)");

                                    b2.Property<decimal>("Temperatura")
                                        .HasPrecision(5, 2)
                                        .HasColumnType("decimal(5,2)");

                                    b2.HasKey("RecepcionLecheId");

                                    b2.ToTable("Recepciones");

                                    b2.WithOwner()
                                        .HasForeignKey("RecepcionLecheId");
                                });

                            b1.Navigation("Parametros")
                                .IsRequired();
                        });

                    b.Navigation("Recepciones");
                });
#pragma warning restore 612, 618
        }
    }
}
